'use client';
import { useEffect, useState } from 'react';
import { Copy, Plus, RefreshCw } from 'lucide-react';

type Contestant = { id: string; name: string; photo_url: string };
type User = { id: string; name: string; token: string };
type Pick = { user_id: string; order_ids: string[] };
type Elim = { contestant_id: string; position: number };
type State = { contestants: Contestant[]; users: User[]; picks: Pick[]; eliminations: Elim[] };

export default function AdminPage() {
 const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [state,setState]=useState<State|null>(null); const [msg,setMsg]=useState('');
 const load=()=>fetch('/api/state').then(r=>r.json()).then(setState); useEffect(()=>{load()},[]);
 async function action(body: Record<string, unknown>) { setMsg(''); const res=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json','x-admin-password':password},body:JSON.stringify(body)}); const data=await res.json(); setMsg(res.ok?'OK':data.error); await load(); return data; }
 const base= typeof window==='undefined'?'':window.location.origin;
 return <main className="mx-auto max-w-7xl px-5 py-10"><a href="/" className="text-sm text-cyan-200">← Home</a><div className="mt-8 spotlight rounded-[2rem] p-6"><p className="text-sm uppercase tracking-[.28em] text-yellow-200">Admin panel</p><h1 className="mt-2 text-5xl font-black">Control de quiniela</h1><p className="mt-3 text-violet-100/70">Crea usuarios, comparte links únicos y actualiza eliminaciones manualmente.</p><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="ADMIN_PASSWORD" type="password" className="mt-6 w-full rounded-2xl border border-white/15 bg-black/30 px-4 py-3 outline-none focus:border-cyan-200" /></div>
 <section className="mt-8 grid gap-6 lg:grid-cols-2"><div className="spotlight rounded-3xl p-5"><h2 className="text-2xl font-black">Usuarios</h2><div className="mt-4 flex gap-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre del participante" className="min-w-0 flex-1 rounded-xl border border-white/15 bg-black/30 px-4 py-3"/><button onClick={()=> action({action:'createUser', name}).then(()=>setName(''))} className="rounded-xl bg-yellow-300 px-4 font-black text-slate-950"><Plus/></button></div><div className="mt-4 space-y-3">{state?.users.map(u=> <div key={u.id} className="rounded-2xl bg-white/6 p-3"><div className="flex items-center justify-between gap-3"><div><p className="font-bold">{u.name}</p><p className="text-xs text-violet-100/50">{state.picks.some(p=>p.user_id===u.id)?'Enviado':'Pendiente'}</p></div><button onClick={()=>navigator.clipboard.writeText(`${base}/join/${u.token}`)} className="rounded-xl border border-white/15 p-2" aria-label="Copiar link"><Copy className="size-4"/></button></div><code className="mt-2 block overflow-x-auto rounded-xl bg-black/30 p-2 text-xs text-cyan-100">{base}/join/{u.token}</code></div>)}</div></div>
 <div className="spotlight rounded-3xl p-5"><div className="flex items-center justify-between"><h2 className="text-2xl font-black">Eliminaciones</h2><button className="rounded-xl border border-white/15 p-2" onClick={()=>action({action:'resetEliminations'})}><RefreshCw className="size-4"/></button></div><button onClick={()=>action({action:'seedContestants'})} className="mt-4 rounded-xl border border-cyan-200/40 px-4 py-2 text-cyan-100">Seed/actualizar cast</button><div className="mt-4 space-y-3">{state?.contestants.map(c=>{const existing=state.eliminations.find(e=>e.contestant_id===c.id);return <div key={c.id} className="flex items-center gap-3 rounded-2xl bg-white/6 p-3"><img src={c.photo_url} alt={c.name} className="size-12 rounded-xl object-cover"/><p className="flex-1 font-bold">{c.name}</p><input defaultValue={existing?.position||''} placeholder="#" type="number" min="1" className="w-20 rounded-xl border border-white/15 bg-black/30 px-3 py-2" onBlur={e=>{const v=Number(e.target.value); if(v) action({action:'setElimination', contestantId:c.id, position:v})}}/></div>})}</div></div></section>{msg&&<p className="mt-5 text-center text-cyan-100">{msg}</p>}</main>
}
